### ISSUE TITLE
Add Scaffold

### ISSUE THREAD

**Issue by freezeOP** [cngege/Mod#2]

**Comment by cngege** [comment]
我不知道你所说的功能如何实现
I don't know how to implement the function you mentioned

**Comment by freezeOP** [comment]
To add Scaffold, add buildBlock to GameMode,

auto pos = player->getPosition();
GameMode::buildBlock(vec3_ti(pos.x, pos.y - 1, pos.z), 0, true);

This won't work with Hive, so I think you should use something like BlockSource to calculate the side of the block and create it.


I don't understand English, so I used translation software.

**Comment by freezeOP** [comment]
If Scaffold is not possible, please add a command (requires SendChatMessage hook)

**Comment by freezeOP** [comment]
virtual void startBuildBlock(vec3_ti const&, unsigned char);
virtual void buildBlock(vec3_ti const&, unsigned char, bool);
This is the old SDK for NukeClient.
(1.20.30)

**Comment by cngege** [comment]
等我将dll兼容最新版之后，再尝试研究这个，之后考虑是否有添加的必要
After I make the dll compatible with the latest version, I will try to study this and then consider whether it is necessary to add it.

**Comment by freezeOP** [comment]
okay, good luck
