### ISSUE TITLE
UPDATE HORION 1.20.41 or make it like horion and add some readable english text thnx

### ISSUE THREAD

**Issue by TheScreams** [cngege/Mod#4]
Make it more horion and add some english text please or you cab update the 1.20.0.1 horion to 1.20.41 and make it imgui supported thanks

**Comment by cngege** [comment]
第一，我没有1.20的客户端去反编译和调试。第二个我现在没有时间和兴趣去做这些，如果你仅是需要当前版本的英文版，可以去下载源代码，将相关中文字符串翻译成英文然后自行使用vs2022编译。
_First, I don't have the 1.20 client to decompile and debug. Second, I don't have the time or interest to do this now. If you just need the English version of the current version, you can download the source code, translate the relevant Chinese strings into English, and then compile them with vs2022 by yourself._

**Comment by TheScreams** [comment]
> 第一，我没有1.20的客户端去反编译和调试。第二个我现在没有时间和兴趣去做这些，如果你仅是需要当前版本的英文版，可以去下载源代码，将相关中文字符串翻译成英文然后自行使用vs2022编译。 _First, I don't have the 1.20 client to decompile and debug. Second, I don't have the time or interest to do this now. If you just need the English version of the current version, you can download the source code, translate the relevant Chinese strings into English, and then compile them with vs2022 by yourself._

**Comment by TheScreams** [comment]
There is a 1.20 Src, it's from Uffuso (his github user) and about the time and we are willing to wait and a lot of people will contribute to it if its updated to 1.20.41+
